name: Dependabot Security Check

on:
  pull_request:
    branches:
      - main  # Or whatever your protected branch is

jobs:
  check-dependabot-alerts:
    runs-on: ubuntu-latest  # Use the default GitHub runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out the pull request code so it can be scanned

      # Step 2: Check for high-risk Dependabot alerts
      - name: Check for high-risk Dependabot alerts
        run: |
          # Fetch Dependabot alerts from the GitHub API
          dependabot_alerts=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts")

          # Count the number of high-risk vulnerabilities
          high_risk_alerts=$(echo $dependabot_alerts | jq '. | map(select(.severity == "high")) | length')

          # If there are any high-risk alerts, fail the job and block the PR from merging
          if [ "$high_risk_alerts" -gt 0 ]; then
            echo "Error: Found $high_risk_alerts high-risk Dependabot alerts. Resolve before merging."
            exit 1  # This stops the PR if high-risk vulnerabilities are found
          else
            echo "No high-risk Dependabot alerts found. Proceeding with the merge."
          fi
