name: JSCPD Code Duplication Check

on:
  pull_request:
    branches:
      - main

jobs:
  jscpd:
    name: Run JSCPD
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JSCPD
        run: npm install -g jscpd

      - name: Run JSCPD for the whole project
        if: ${{ inputs.scope == 'project' }}
        run: jscpd --reporters console,markdown,sarif --output report --threshold ${{ inputs.threshold }} --gitignore

      - name: Run JSCPD on changed files
        if: ${{ inputs.scope == 'pull_request' }}
        run: |
          FILES=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --name-only)
          echo "$FILES"
          jscpd --reporters console,markdown,sarif --output report --threshold ${{ inputs.threshold }} --gitignore $FILES

      - name: Check if report exists and set variable
        run: |
          if [ -f report/jscpd-report.md ]; then
            echo "report_exists=true" >> $GITHUB_ENV
          else
            echo "report_exists=false" >> $GITHUB_ENV
          fi

      - name: Upload JSCPD Report
        if: (success() || failure()) && env.report_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: jscpd-report
          path: report

      - name: Comment JSCPD results on PR
        if: (success() || failure()) && github.event_name == 'pull_request' && env.report_exists == 'true'
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: report/jscpd-report.md
          comment-tag: jscpd-bot

      # Upload scan results to GitHub Security tab
      - name: Upload jspcd scan results to GitHub Security tab
        if: success() && env.report_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: 'report/jscpd-sarif.json'
