name: JSCPD Code Duplication Check

on:
  pull_request:
    branches:
      - main

jobs:
  jscpd:
    name: Run JSCPD
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for git diff

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JSCPD
        run: npm install -g jscpd

      - name: Debug Changed Files
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

      - name: Run JSCPD on changed Python files
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.py$' || true)
          
          if [[ -z "$FILES" ]]; then
            echo "No Python files detected, skipping JSCPD."
            exit 0
          fi
          
          echo "Scanning changed Python files: $FILES"
          jscpd --reporters console,markdown,sarif --output report --threshold 2 --gitignore $FILES

      - name: Check if report exists and set variable
        run: |
          if [ -f report/jscpd-report.md ]; then
            echo "report_exists=true" >> $GITHUB_ENV
          else
            echo "report_exists=false" >> $GITHUB_ENV
          fi

      - name: Debug report variable
        run: echo "Report exists: ${{ env.report_exists }}"

      - name: Upload JSCPD Report
        if: (success() || failure()) && env.report_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: jscpd-report
          path: report

      - name: Comment JSCPD results on PR
        if: (success() || failure()) && github.event_name == 'pull_request' && env.report_exists == 'true'
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: report/jscpd-report.md
          comment-tag: jscpd-bot

      - name: Upload JSCPD scan results to GitHub Security tab
        if: success() && env.report_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'report/jscpd-sarif.json'
